spring.application.name=crudSpringBoot
spring.datasource.url=jbdc-url/student_crud_db
spring.datasource.username=your-username
spring.datasource.password=your-password

spring.jpa.hibernate.ddl-auto=update
